# Generated by Django 5.1.2 on 2024-10-23 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_employeedata_time_duration_of_efficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='efficiency',
            field=models.CharField(choices=[('Exceptional', 'Exceptional'), ('Very Good', 'Very Good'), ('Above Average', 'Above Average'), ('Average', 'Average'), ('Below Average', 'Below Average')], max_length=30),
        ),
    ]
