# Generated by Django 5.1.2 on 2024-10-22 04:13

import datetime
from django.db import migrations, models

def set_default_start_time(apps, schema_editor):
    User = apps.get_model('user', 'User')
    default_time = datetime.datetime(2024, 10, 22,)  # set your desired default time here
    default_dob = datetime.datetime(2000, 1, 24,)  # set your desired default time here
    for user in User.objects.filter(date_joined__isnull=True):
        user.date_joined = default_time
        user.save()
    for user in User.objects.filter(dob__isnull=True):
        user.dob = default_dob
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='add it now', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateTimeField(default=datetime.datetime(2000, 1, 24, 0, 0)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
         migrations.RunPython(set_default_start_time),
    ]
