# Generated by Django 5.1.2 on 2024-10-22 04:35

import datetime
from django.db import migrations, models
def set_default_start_time(apps, schema_editor):
    User = apps.get_model('user', 'User')
    default_time = datetime.date(2024, 10, 22,)  # set your desired default time here
    # for i in range(4):
    #     user = User.objects.get(id = i)
    #     print(user.id)
    for user in User.objects.all():
        print(str(default_time))
        print(user.id)
        user.date_joined=default_time
        user.save()

class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_date_joined_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default='add it noww', max_length=100),
        ),
         migrations.RunPython(set_default_start_time),

    ]
