# Generated by Django 5.1.2 on 2024-10-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_employeedata_time_duration_of_efficiency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedata',
            old_name='efficiency',
            new_name='assesment',
        ),
        migrations.RenameField(
            model_name='employeedata',
            old_name='time_duration_of_efficiency',
            new_name='assesment_year',
        ),
    ]
