# Generated by Django 5.1.2 on 2024-10-23 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_efficiency_employeedata_assesment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeedata',
            old_name='employee_id',
            new_name='employee',
        ),
    ]
