# Generated by Django 5.1.2 on 2024-10-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_employee_id_employeedata_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(),
        ),
    ]
